import { Box, Flex } from '@chakra-ui/react'
import Head from 'next/head'
import Image from 'next/image'
import Sidebar from '../components/Sidebar'


export default function Home() {
  return (
    <>
      <Head>
        <title>chatify</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='flex '>
        
      <Box h="100vh">
        <Sidebar />


      </Box>
      <div className='w-[80%]  m-auto justify-center items-center'>
        
        <img className='w-[20%] m-auto' src="https://media4.giphy.com/media/26FPJGjhefSJuaRhu/200.webp?cid=ecf05e47vvc8r6jtnag03k2zvxnx4pugb7krfq0gcmt6ofr8&rid=200.webp&ct=g" alt=""/>
        <h2 className='text-center md:text-3xl text-xl font-serif '>"Select a chat to begin with"</h2>
      </div>
      </div>
</>
  )
}
