import { Box } from '@chakra-ui/react'
import Head from 'next/head'
import Image from 'next/image'
import Sidebar from '../components/Sidebar'


export default function Home() {
  return (
    <>
      <Head>
        <title>chatify</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box h="100vh">
        <Sidebar/>
      </Box>
</>
  )
}
